-- PackTogether Supabase schema (fresh start)
-- Run this file first.

begin;

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  name text not null check (char_length(trim(name)) between 1 and 80),
  departure_at timestamptz not null,
  status text not null default 'packing' check (status in ('packing', 'locked')),
  created_by bigint not null,
  created_at timestamptz not null default now()
);

-- Only one active trip per group/chat.
create unique index if not exists trips_one_active_per_chat
  on public.trips (chat_id)
  where status = 'packing';

create index if not exists trips_chat_id_idx on public.trips (chat_id);
create index if not exists trips_created_at_idx on public.trips (created_at desc);
create index if not exists trips_departure_at_idx on public.trips (departure_at);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 200),
  created_by bigint not null,
  created_at timestamptz not null default now(),
  status text not null default 'unchecked' check (status in ('checked', 'unchecked', 'deleted'))
);

create index if not exists items_trip_id_idx on public.items (trip_id);
create index if not exists items_trip_status_idx on public.items (trip_id, status);
create index if not exists items_created_at_idx on public.items (created_at desc);

create table if not exists public.actions_history (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade,
  item_id bigint references public.items(id) on delete set null,
  type text not null,
  "desc" text not null,
  actor text not null,
  "timestamp" timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '72 hours')
);

create index if not exists actions_history_trip_id_idx on public.actions_history (trip_id);
create index if not exists actions_history_timestamp_idx on public.actions_history ("timestamp" desc);
create index if not exists actions_history_expires_at_idx on public.actions_history (expires_at);

commit;
