from __future__ import annotations

import os
import sqlite3
import threading
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

import httpx
import psycopg
from psycopg.rows import dict_row

SQLITE_SCHEMA = """
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS trips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    departure_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'packing' CHECK(status IN ('packing', 'locked')),
    created_by INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_by INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'unchecked' CHECK(status IN ('checked', 'unchecked', 'deleted'))
);

CREATE TABLE IF NOT EXISTS actions_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id INTEGER REFERENCES trips(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES items(id) ON DELETE SET NULL,
    type TEXT NOT NULL,
    "desc" TEXT NOT NULL,
    actor TEXT NOT NULL,
    "timestamp" TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_state (
    id INTEGER PRIMARY KEY CHECK(id = 1),
    dirty INTEGER NOT NULL DEFAULT 0,
    dirty_since TEXT,
    last_local_action_at TEXT,
    unsynced_actions INTEGER NOT NULL DEFAULT 0,
    last_sync_started_at TEXT,
    last_sync_completed_at TEXT,
    last_sync_status TEXT,
    last_error TEXT
);
INSERT OR IGNORE INTO sync_state(id, dirty, unsynced_actions) VALUES (1, 0, 0);
"""


SQLITE_INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS trips_one_active_per_chat ON trips(chat_id) WHERE status='packing';
CREATE INDEX IF NOT EXISTS trips_chat_id_idx ON trips(chat_id);
CREATE INDEX IF NOT EXISTS trips_created_at_idx ON trips(created_at DESC);
CREATE INDEX IF NOT EXISTS trips_departure_at_idx ON trips(departure_at);
CREATE INDEX IF NOT EXISTS items_trip_id_idx ON items(trip_id);
CREATE INDEX IF NOT EXISTS items_trip_status_idx ON items(trip_id, status);
CREATE INDEX IF NOT EXISTS items_created_at_idx ON items(created_at DESC);
CREATE INDEX IF NOT EXISTS actions_history_trip_id_idx ON actions_history(trip_id);
CREATE INDEX IF NOT EXISTS actions_history_timestamp_idx ON actions_history("timestamp" DESC);
CREATE INDEX IF NOT EXISTS actions_history_expires_at_idx ON actions_history(expires_at);
"""


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS public.trips (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  name text not null check (char_length(trim(name)) between 1 and 80),
  departure_at timestamptz not null,
  status text not null default 'packing' check (status in ('packing', 'locked')),
  created_by bigint not null,
  created_at timestamptz not null default now()
);
CREATE UNIQUE INDEX IF NOT EXISTS trips_one_active_per_chat
  ON public.trips (chat_id)
  WHERE status = 'packing';
CREATE INDEX IF NOT EXISTS trips_chat_id_idx ON public.trips (chat_id);
CREATE INDEX IF NOT EXISTS trips_created_at_idx ON public.trips (created_at DESC);
CREATE INDEX IF NOT EXISTS trips_departure_at_idx ON public.trips (departure_at);

CREATE TABLE IF NOT EXISTS public.items (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 200),
  created_by bigint not null,
  created_at timestamptz not null default now(),
  status text not null default 'unchecked' check (status in ('checked', 'unchecked', 'deleted'))
);
CREATE INDEX IF NOT EXISTS items_trip_id_idx ON public.items (trip_id);
CREATE INDEX IF NOT EXISTS items_trip_status_idx ON public.items (trip_id, status);
CREATE INDEX IF NOT EXISTS items_created_at_idx ON public.items (created_at DESC);

CREATE TABLE IF NOT EXISTS public.actions_history (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade,
  item_id bigint references public.items(id) on delete set null,
  type text not null,
  "desc" text not null,
  actor text not null,
  "timestamp" timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '72 hours')
);
CREATE INDEX IF NOT EXISTS actions_history_trip_id_idx ON public.actions_history (trip_id);
CREATE INDEX IF NOT EXISTS actions_history_timestamp_idx ON public.actions_history ("timestamp" DESC);
CREATE INDEX IF NOT EXISTS actions_history_expires_at_idx ON public.actions_history (expires_at);
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class Database:
    def __init__(self, dsn_or_path: str | Path):
        self.path = str(dsn_or_path)
        self._transaction_lock = threading.RLock()
        self._is_postgres = self.path.startswith("postgres://") or self.path.startswith("postgresql://")

        if self._is_postgres:
            self.connection = psycopg.connect(self.path, row_factory=dict_row)
            self.connection.autocommit = True
            with self.connection.cursor() as cur:
                cur.execute(POSTGRES_SCHEMA)
        else:
            self.connection = sqlite3.connect(self.path, check_same_thread=False, timeout=30, isolation_level=None)
            self.connection.row_factory = sqlite3.Row
            self.connection.execute("PRAGMA journal_mode=WAL")
            self.connection.execute("PRAGMA busy_timeout=30000")
            self.connection.executescript(SQLITE_SCHEMA)
            self._migrate_sqlite_schema()
            self.connection.executescript(SQLITE_INDEXES)

    def _sqlite_has_column(self, table: str, column: str) -> bool:
        rows = self.connection.execute(f"PRAGMA table_info({table})").fetchall()
        return any(str(row[1]) == column for row in rows)

    def _sqlite_item_columns(self) -> list[str]:
        rows = self.connection.execute("PRAGMA table_info(items)").fetchall()
        return [str(row[1]) for row in rows]

    def _rebuild_items_table_if_legacy_position(self) -> None:
        columns = self._sqlite_item_columns()
        if "position" not in columns:
            return

        has_created_by = "created_by" in columns
        has_created_at = "created_at" in columns
        has_status = "status" in columns

        select_created_by = "created_by" if has_created_by else "0"
        select_created_at = "created_at" if has_created_at else "''"
        select_status = "status" if has_status else "'unchecked'"

        # Legacy schema had NOT NULL items.position with no default.
        # Rebuild table to current schema so inserts without position succeed.
        self.connection.execute("PRAGMA foreign_keys=OFF")
        try:
            self.connection.execute(
                """
                CREATE TABLE IF NOT EXISTS items_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
                    name TEXT NOT NULL,
                    created_by INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'unchecked' CHECK(status IN ('checked', 'unchecked', 'deleted'))
                )
                """
            )
            self.connection.execute(
                f"""
                INSERT INTO items_new(id, trip_id, name, created_by, created_at, status)
                SELECT id,
                       trip_id,
                       name,
                       COALESCE({select_created_by}, 0),
                       COALESCE({select_created_at}, ''),
                       COALESCE({select_status}, 'unchecked')
                FROM items
                """
            )
            self.connection.execute("DROP TABLE items")
            self.connection.execute("ALTER TABLE items_new RENAME TO items")
        finally:
            self.connection.execute("PRAGMA foreign_keys=ON")

    def _migrate_sqlite_schema(self) -> None:
        # Legacy DBs might miss recently-added columns. Add them before index creation.
        self._rebuild_items_table_if_legacy_position()

        if not self._sqlite_has_column("trips", "status"):
            self.connection.execute("ALTER TABLE trips ADD COLUMN status TEXT NOT NULL DEFAULT 'packing'")
        if not self._sqlite_has_column("trips", "created_by"):
            self.connection.execute("ALTER TABLE trips ADD COLUMN created_by INTEGER NOT NULL DEFAULT 0")
        if not self._sqlite_has_column("trips", "created_at"):
            self.connection.execute("ALTER TABLE trips ADD COLUMN created_at TEXT NOT NULL DEFAULT ''")

        if not self._sqlite_has_column("items", "created_by"):
            self.connection.execute("ALTER TABLE items ADD COLUMN created_by INTEGER NOT NULL DEFAULT 0")
        if not self._sqlite_has_column("items", "created_at"):
            self.connection.execute("ALTER TABLE items ADD COLUMN created_at TEXT NOT NULL DEFAULT ''")
        if not self._sqlite_has_column("items", "status"):
            self.connection.execute("ALTER TABLE items ADD COLUMN status TEXT NOT NULL DEFAULT 'unchecked'")

        if not self._sqlite_has_column("actions_history", "expires_at"):
            self.connection.execute("ALTER TABLE actions_history ADD COLUMN expires_at TEXT NOT NULL DEFAULT ''")

        self.connection.execute(
            """
            CREATE TABLE IF NOT EXISTS sync_state (
                id INTEGER PRIMARY KEY CHECK(id = 1),
                dirty INTEGER NOT NULL DEFAULT 0,
                dirty_since TEXT,
                last_local_action_at TEXT,
                unsynced_actions INTEGER NOT NULL DEFAULT 0,
                last_sync_started_at TEXT,
                last_sync_completed_at TEXT,
                last_sync_status TEXT,
                last_error TEXT
            )
            """
        )
        self.connection.execute("INSERT OR IGNORE INTO sync_state(id, dirty, unsynced_actions) VALUES (1, 0, 0)")

    @property
    def is_postgres(self) -> bool:
        return self._is_postgres

    def _sql(self, query: str) -> str:
        return query.replace("?", "%s") if self._is_postgres else query

    def execute(self, query: str, params: tuple[Any, ...] = ()) -> int:
        sql = self._sql(query)
        if self._is_postgres:
            with self.connection.cursor() as cur:
                cur.execute(sql, params)
                return cur.rowcount
        cursor = self.connection.execute(sql, params)
        return int(cursor.rowcount)

    def fetchone(self, query: str, params: tuple[Any, ...] = ()) -> dict[str, Any] | None:
        sql = self._sql(query)
        if self._is_postgres:
            with self.connection.cursor() as cur:
                cur.execute(sql, params)
                row = cur.fetchone()
                return dict(row) if row is not None else None
        row = self.connection.execute(sql, params).fetchone()
        return dict(row) if row is not None else None

    def fetchall(self, query: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
        sql = self._sql(query)
        if self._is_postgres:
            with self.connection.cursor() as cur:
                cur.execute(sql, params)
                return [dict(row) for row in cur.fetchall()]
        rows = self.connection.execute(sql, params).fetchall()
        return [dict(row) for row in rows]

    def scalar(self, query: str, params: tuple[Any, ...] = ()) -> Any:
        row = self.fetchone(query, params)
        if not row:
            return None
        return next(iter(row.values()))

    def insert_returning_id(self, query: str, params: tuple[Any, ...] = ()) -> int:
        sql = self._sql(query)
        if self._is_postgres:
            with self.connection.cursor() as cur:
                cur.execute(sql, params)
                row = cur.fetchone()
                if row is None:
                    raise RuntimeError("Insert did not return id")
                return int(next(iter(row.values())))
        cursor = self.connection.execute(sql, params)
        return int(cursor.lastrowid)

    @contextmanager
    def transaction(self) -> Iterator[Database]:
        with self._transaction_lock:
            if self._is_postgres:
                with self.connection.transaction():
                    yield self
            else:
                self.connection.execute("BEGIN IMMEDIATE")
                try:
                    yield self
                    self.connection.commit()
                except Exception:
                    self.connection.rollback()
                    raise

    def close(self) -> None:
        self.connection.close()

    def mark_dirty_action(self) -> None:
        timestamp = now_iso()
        self.execute(
            """
            UPDATE sync_state
            SET dirty=1,
                dirty_since=COALESCE(dirty_since, ?),
                last_local_action_at=?,
                unsynced_actions=unsynced_actions+1
            WHERE id=1
            """,
            (timestamp, timestamp),
        )

    def get_sync_state(self) -> dict[str, Any]:
        row = self.fetchone("SELECT * FROM sync_state WHERE id=1")
        if row is None:
            return {
                "id": 1,
                "dirty": 0,
                "dirty_since": None,
                "last_local_action_at": None,
                "unsynced_actions": 0,
                "last_sync_started_at": None,
                "last_sync_completed_at": None,
                "last_sync_status": None,
                "last_error": None,
            }
        return row

    def mark_sync_started(self) -> None:
        self.execute(
            "UPDATE sync_state SET last_sync_started_at=?, last_error=NULL WHERE id=1",
            (now_iso(),),
        )

    def mark_sync_succeeded(self) -> None:
        timestamp = now_iso()
        self.execute(
            """
            UPDATE sync_state
            SET dirty=0,
                dirty_since=NULL,
                unsynced_actions=0,
                last_sync_completed_at=?,
                last_sync_status='ok',
                last_error=NULL
            WHERE id=1
            """,
            (timestamp,),
        )

    def mark_sync_failed(self, error_message: str) -> None:
        timestamp = now_iso()
        self.execute(
            """
            UPDATE sync_state
            SET last_sync_completed_at=?,
                last_sync_status='failed',
                last_error=?
            WHERE id=1
            """,
            (timestamp, error_message[:1000]),
        )


class SupabaseApiDatabase:
    def __init__(self, url: str, service_role_key: str):
        from supabase import create_client
        from supabase.client import ClientOptions

        cleaned_url = (url or "").strip().rstrip("/")
        if not cleaned_url.startswith("https://"):
            raise ValueError("SUPABASE_URL must start with https://")

        self.url = cleaned_url
        self._transaction_lock = threading.RLock()
        # Avoid inheriting OS/env HTTP proxies that can break TLS hostname checks.
        http_client = httpx.Client(trust_env=False, timeout=30.0)
        options = ClientOptions(httpx_client=http_client)
        self.client = create_client(cleaned_url, service_role_key, options)

    @property
    def is_postgres(self) -> bool:
        return False

    @staticmethod
    def _normalize_sql(query: str) -> str:
        return " ".join(query.strip().split())

    def execute(self, query: str, params: tuple[Any, ...] = ()) -> int:
        q = self._normalize_sql(query)

        if q == "UPDATE trips SET status='locked' WHERE id=? AND status='packing'":
            trip_id = int(params[0])
            current = self.client.table("trips").select("id,status").eq("id", trip_id).eq("status", "packing").limit(1).execute().data
            if not current:
                return 0
            self.client.table("trips").update({"status": "locked"}).eq("id", trip_id).eq("status", "packing").execute()
            return 1

        if q == "UPDATE items SET status=? WHERE id=?":
            status, item_id = str(params[0]), int(params[1])
            self.client.table("items").update({"status": status}).eq("id", item_id).execute()
            return 1

        if q == "UPDATE items SET status='deleted' WHERE id=?":
            item_id = int(params[0])
            self.client.table("items").update({"status": "deleted"}).eq("id", item_id).execute()
            return 1

        if q == 'INSERT INTO actions_history(trip_id,item_id,type,"desc",actor,"timestamp",expires_at) VALUES(?,?,?,?,?,?,?)':
            trip_id, item_id, action_type, desc, actor, ts, expires_at = params
            self.client.table("actions_history").insert(
                {
                    "trip_id": int(trip_id),
                    "item_id": None if item_id is None else int(item_id),
                    "type": str(action_type),
                    "desc": str(desc),
                    "actor": str(actor),
                    "timestamp": str(ts),
                    "expires_at": str(expires_at),
                }
            ).execute()
            return 1

        raise NotImplementedError(f"Unsupported execute query for Supabase API backend: {query}")

    def fetchone(self, query: str, params: tuple[Any, ...] = ()) -> dict[str, Any] | None:
        rows = self.fetchall(query, params)
        return rows[0] if rows else None

    def fetchall(self, query: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
        q = self._normalize_sql(query)

        if q == "SELECT id FROM trips WHERE chat_id=? AND status='packing'":
            chat_id = int(params[0])
            return self.client.table("trips").select("id").eq("chat_id", chat_id).eq("status", "packing").limit(1).execute().data or []

        if q == "SELECT * FROM trips WHERE chat_id=? AND status='packing'":
            chat_id = int(params[0])
            return self.client.table("trips").select("*").eq("chat_id", chat_id).eq("status", "packing").execute().data or []

        if q == "SELECT * FROM trips WHERE chat_id=? ORDER BY id DESC LIMIT 1":
            chat_id = int(params[0])
            return self.client.table("trips").select("*").eq("chat_id", chat_id).order("id", desc=True).limit(1).execute().data or []

        if q == "SELECT * FROM trips WHERE chat_id=? AND status='packing' ORDER BY id DESC LIMIT 1":
            chat_id = int(params[0])
            return self.client.table("trips").select("*").eq("chat_id", chat_id).eq("status", "packing").order("id", desc=True).limit(1).execute().data or []

        if q == "SELECT * FROM trips WHERE id=?":
            trip_id = int(params[0])
            return self.client.table("trips").select("*").eq("id", trip_id).limit(1).execute().data or []

        if q == "SELECT * FROM trips WHERE status='packing'":
            return self.client.table("trips").select("*").eq("status", "packing").execute().data or []

        if q.startswith("SELECT * FROM items WHERE trip_id=? AND status <> 'deleted' AND id IN ("):
            trip_id = int(params[0])
            ids = [int(v) for v in params[1:]]
            if not ids:
                return []
            return (
                self.client.table("items")
                .select("*")
                .eq("trip_id", trip_id)
                .neq("status", "deleted")
                .in_("id", ids)
                .execute()
                .data
                or []
            )

        if q == "SELECT * FROM items WHERE id=? AND trip_id=? AND status <> 'deleted'":
            item_id, trip_id = int(params[0]), int(params[1])
            return (
                self.client.table("items")
                .select("*")
                .eq("id", item_id)
                .eq("trip_id", trip_id)
                .neq("status", "deleted")
                .limit(1)
                .execute()
                .data
                or []
            )

        if q == "SELECT id, trip_id, name, created_by, created_at, status FROM items WHERE trip_id=? AND status <> 'deleted' ORDER BY id LIMIT ? OFFSET ?":
            trip_id, limit, offset = int(params[0]), int(params[1]), int(params[2])
            end = max(offset + limit - 1, offset)
            return (
                self.client.table("items")
                .select("id,trip_id,name,created_by,created_at,status")
                .eq("trip_id", trip_id)
                .neq("status", "deleted")
                .order("id")
                .range(offset, end)
                .execute()
                .data
                or []
            )

        if q == "SELECT name FROM items WHERE id=? AND trip_id=? AND status <> 'deleted'":
            item_id, trip_id = int(params[0]), int(params[1])
            return (
                self.client.table("items")
                .select("name")
                .eq("id", item_id)
                .eq("trip_id", trip_id)
                .neq("status", "deleted")
                .limit(1)
                .execute()
                .data
                or []
            )

        if q.startswith("SELECT id, name FROM items WHERE id IN ("):
            ids = [int(v) for v in params]
            if not ids:
                return []
            return (
                self.client.table("items")
                .select("id,name")
                .in_("id", ids)
                .execute()
                .data
                or []
            )

        if q == 'SELECT id, trip_id, item_id, type, "desc", actor, "timestamp" FROM actions_history WHERE trip_id=? ORDER BY id DESC LIMIT ?':
            trip_id, limit = int(params[0]), int(params[1])
            return (
                self.client.table("actions_history")
                .select("id,trip_id,item_id,type,desc,actor,timestamp")
                .eq("trip_id", trip_id)
                .order("id", desc=True)
                .limit(limit)
                .execute()
                .data
                or []
            )

        if q == "SELECT type, actor FROM actions_history WHERE item_id=? ORDER BY id":
            item_id = int(params[0])
            return (
                self.client.table("actions_history")
                .select("type,actor")
                .eq("item_id", item_id)
                .order("id")
                .execute()
                .data
                or []
            )

        if q == "SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status='checked') AS claimed FROM items WHERE trip_id=? AND status <> 'deleted'":
            trip_id = int(params[0])
            rows = self.client.table("items").select("status").eq("trip_id", trip_id).neq("status", "deleted").execute().data or []
            total = len(rows)
            claimed = sum(1 for row in rows if row.get("status") == "checked")
            return [{"total": total, "claimed": claimed}]

        if q == "SELECT COUNT(*) FROM items WHERE trip_id=? AND status <> 'deleted'":
            trip_id = int(params[0])
            count = self.client.table("items").select("id", count="exact").eq("trip_id", trip_id).neq("status", "deleted").execute().count or 0
            return [{"count": int(count)}]

        if q == "SELECT COUNT(*) FROM trips WHERE chat_id=?":
            chat_id = int(params[0])
            count = self.client.table("trips").select("id", count="exact").eq("chat_id", chat_id).execute().count or 0
            return [{"count": int(count)}]

        if q == "SELECT COUNT(*) FROM trips WHERE chat_id=? AND status='packing'":
            chat_id = int(params[0])
            count = self.client.table("trips").select("id", count="exact").eq("chat_id", chat_id).eq("status", "packing").execute().count or 0
            return [{"count": int(count)}]

        raise NotImplementedError(f"Unsupported fetch query for Supabase API backend: {query}")

    def scalar(self, query: str, params: tuple[Any, ...] = ()) -> Any:
        row = self.fetchone(query, params)
        if not row:
            return None
        return next(iter(row.values()))

    def insert_returning_id(self, query: str, params: tuple[Any, ...] = ()) -> int:
        q = self._normalize_sql(query)

        if q == "INSERT INTO trips(chat_id,name,departure_at,status,created_by,created_at) VALUES(?,?,?,?,?,?) RETURNING id":
            chat_id, name, departure_at, status, created_by, created_at = params
            data = (
                self.client.table("trips")
                .insert(
                    {
                        "chat_id": int(chat_id),
                        "name": str(name),
                        "departure_at": str(departure_at),
                        "status": str(status),
                        "created_by": int(created_by),
                        "created_at": str(created_at),
                    }
                )
                .execute()
                .data
                or []
            )
            if not data:
                raise RuntimeError("Insert into trips did not return id")
            return int(data[0]["id"])

        if q == "INSERT INTO items(trip_id,name,created_by,created_at,status) VALUES(?,?,?,?,?) RETURNING id":
            trip_id, name, created_by, created_at, status = params
            data = (
                self.client.table("items")
                .insert(
                    {
                        "trip_id": int(trip_id),
                        "name": str(name),
                        "created_by": int(created_by),
                        "created_at": str(created_at),
                        "status": str(status),
                    }
                )
                .execute()
                .data
                or []
            )
            if not data:
                raise RuntimeError("Insert into items did not return id")
            return int(data[0]["id"])

        raise NotImplementedError(f"Unsupported insert query for Supabase API backend: {query}")

    @contextmanager
    def transaction(self) -> Iterator[SupabaseApiDatabase]:
        # PostgREST does not provide client-side multi-statement DB transactions.
        # Keep an in-process critical section for best-effort consistency.
        with self._transaction_lock:
            yield self

    def close(self) -> None:
        return

    @staticmethod
    def _chunk(rows: list[dict[str, Any]], size: int = 200) -> Iterator[list[dict[str, Any]]]:
        for index in range(0, len(rows), size):
            yield rows[index:index + size]

    def upsert_snapshot(self, *, trips: list[dict[str, Any]], items: list[dict[str, Any]], actions: list[dict[str, Any]]) -> dict[str, int]:
        sent = {"trips": 0, "items": 0, "actions": 0}
        for batch in self._chunk(trips):
            if batch:
                self.client.table("trips").upsert(batch, on_conflict="id").execute()
                sent["trips"] += len(batch)
        for batch in self._chunk(items):
            if batch:
                self.client.table("items").upsert(batch, on_conflict="id").execute()
                sent["items"] += len(batch)
        for batch in self._chunk(actions):
            if batch:
                self.client.table("actions_history").upsert(batch, on_conflict="id").execute()
                sent["actions"] += len(batch)
        return sent


def database_from_env() -> Database:
    return Database(os.getenv("DATABASE_PATH", "packtogether.sqlite3"))


def mirror_from_env() -> SupabaseApiDatabase | None:
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_service_role_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if supabase_url and supabase_service_role_key:
        return SupabaseApiDatabase(supabase_url, supabase_service_role_key)

    return None
